print("PRUEBAS GIT")
print("PRIMERA LINEA DE COMANDOS")
print("Esta es la segunda linea para hacer un checkout con git")
print("Esta es otra linea para hacer un diff y ver como se muestra que ha habido cambios")
print("Esta es otra linea para hacer un diff y ver como se muestra que ha habido cambios Version 2.0")